nome = input('Digite o seu nome: ')
idade = input('Digite sua idade: ')
print ('Abaixo você deve escrever sua data de nascimento.')
dia = input('Dia: ')
mes = input('Mês: ')
ano = input('Ano: ')
print ('Agora você vai colocar seu endereço.')
pais = input('País: ')
estado = input('Estado: ')
cidade = input('Cidade: ')
print (nome, ' tem ', idade, ' anos e nasceu dia ', dia, ' de ', mes, ' de ', ano)
print (nome, ' mora no ', pais, ' no estado de ', estado, ' e na cidade de ', cidade)
