p1 = str(input('Digite uma frase: '))
p2 = str(input('Digite uma frase: '))
print(f'String 1: {p1}')
print(f'String 2: {p2}')
print(f'Tamanho de "{p1}": {len(p1)} caracteres.')
print(f'Tamanho de "{p2}": {len(p2)} caracteres.')
print(f'As duas strings tem o mesmo número de caracteres? {(len(p1)) == (len(p2))}')
print(f'As duas strings possuem o mesmo conteúdo? {p1 == p2}')
print(p1[::-1])