n1 = int(input('Digite o primeiro valor: '))
n2 = int(input('Digite o segundo valor: '))
print(f'A soma de {n1} e {n2} é igual a {n1+n2}')
print(f'A subtração de {n1} e {n2} é igual a {n1-n2}')
print(f'O número {n1} vezes {n2} é igual a {n1*n2}')
print(f'O número {n1} dividido por {n2} é igual a {n1/n2:.2f}')
print(f'O número {n2} dividido por {n1} é igual a {n2/n1:.2f}')
print(f'O número {n1} elevado a {n2} é igual a {n1**n2}')
print(f'O número {n2} elevado a {n1} é igual a {n2**n1}')
print(f'A divisão inteira entre {n1} e {n2} é igual a {n1//n2}')
print(f'A divisão inteira entre {n2} e {n1} é igual a {n2//n1}')
print(f'O resto da divisão entre {n1} e {n2} é igual a {n1%n2}')
print(f'O resto da divisão entre {n2} e {n1} é igual a {n2%n1}')
# USE , end=" ") NO FINAL PARA CONTINUAÇÃO DE PRINT
# USE \n PARA PULAR LINHA NO PRINT