metros = float(input('Digite uma distância em metros: '))
print(f'A distância de {metros} metros corresponde a:')
print(f'{metros/1000}Km                       {metros*10}Dm')
print(f'{metros/100}Hm                        {metros*100}Cm')
print(f'{metros/10}Dam                        {metros*1000}Mm')